[tool.poetry]
name = "path-tmpl-worker"
version = "0.4.0"
description = "Path template worker"
authors = ["Eugen Ciur <eugen@papermerge.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
sqlalchemy = "^2.0.42"
pydantic-settings = "^2.10"
pydantic = "^2.11"
typer = "^0.16.0"
pathtmpl = "0.2.0"
celery = {version = "^5.5", extras = ["redis"]}
pyyaml = "^6.0.2"
redis = "^5.3"
psycopg2 = { version = "^2.9.2", optional = true}

[tool.poetry.extras]
pg = ["psycopg2"]

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
taskipy = "^1.14.1"

[tool.poetry.scripts]
pathtmpl = 'path_tmpl_worker.cli.main:app'


[tool.taskipy.tasks]
worker = "celery -A path_tmpl_worker.celery_app worker -E -c 4 -Q path_tmpl"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
