[project]
name = "path-tmpl-worker"
version = "0.5"
description = "Path template worker"
authors = [
    { name = "Eugen Ciur", email = "eugen@papermerge.com" }
]
readme = "README.md"
requires-python = ">=3.13,<4"
dependencies = [
    "sqlalchemy",
    "pydantic-settings",
    "pydantic",
    "typer",
    "pathtmpl",
    "celery[redis]",
    "pyyaml",
    "redis",
     "psycopg2-binary"
]

[project.scripts]
pathtmpl = "path_tmpl_worker.cli.main:app"

[project.optional-dependencies]
dev = ["pytest", "taskipy", "freezegun"]

[tool.taskipy.tasks]
worker = "celery -A path_tmpl_worker.celery_app worker -E -c 4 -Q path_tmpl"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
