name: Tests

on: push

jobs:
  tests_with_sqlite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Run Tests
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install && poetry run pytest
        env:
          PAPERMERGE__DATABASE__URL: 'sqlite:///test.sqlite'
  tests_with_postgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.1
        env:
          POSTGRES_PASSWORD: pmgpass
          POSTGRES_USER: pmguser
          POSTGRES_DB: test_pmgdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Run Tests
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install -E pg && poetry run pytest
        env:
          PAPERMERGE__DATABASE__URL: 'postgresql://pmguser:pmgpass@localhost:5432/test_pmgdb'
